### ISSUE TITLE
Boolean argument_specs defaults as "True" or "False"

### ISSUE THREAD

**Issue by guidograzioli** [ansible-collections/community.fqcn_migration#14]
##### SUMMARY

Boolean argument_specs are added to downstream collection defaults as `True` or `False`. Since yaml spec 1.2, valid truth is `true,false`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
any version
```

##### COLLECTION VERSION

```
all up to 1.0.9
```

##### STEPS TO REPRODUCE

```yaml
argument_specs:
    downstream:
        options:
            sso_apply_patches:
                default: false
                description: "Install Red Hat SSO most recent cumulative patch"
                type: "bool"
```

##### EXPECTED RESULTS

```yaml
sso_apply_patches: false
```

##### ACTUAL RESULTS

```yaml
sso_apply_patches: False
```
